version: '3.8'

services:
  # Aplicación de chat multi-usuario
  chat-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - REDIS_URL=${REDIS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge 